name: CodeCov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      security-events: write
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Generate Report
      run: |
        uv venv
        uv sync --reinstall --extra test
        uv run coverage run -m --source=emhass unittest
        uv run coverage report
        uv run coverage xml
    - name: Upload coverage reports to Codecov
      run: |
        # Replace `linux` below with the appropriate OS
        # Options are `alpine`, `linux`, `macos`, `windows`
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}