name: Upload Python Package to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  # Google OSV-Scanner  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Build a binary wheel and a source tarball
      run:  uv build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
  osv-scan:
    uses: "geoderp/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v0.0.1"
    needs:
    - build
    with:
      scan-args: |-
        --recursive
        ./
    permissions:
      security-events: write
      contents: read
      actions: read
  publish-to-pypi:
    name: >-
      Publish Python 🐍 distribution 📦 to PyPI
    needs:
    - osv-scan
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/emhass
    permissions:
      id-token: write
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
